# Generated by Django 4.1.5 on 2023-01-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('day', models.CharField(choices=[('Понедельник', 'Пн'), ('Вторник', 'Вт'), ('Среда', 'Ср'), ('Четверг', 'Чт'), ('Пятница', 'Пт'), ('Суббота', 'Суб'), ('Воскресение', 'Вос')], max_length=15, verbose_name='День')),
                ('opera', models.CharField(max_length=100, verbose_name='Опера')),
                ('balet', models.CharField(max_length=100, verbose_name='Балет')),
            ],
            options={
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opera.table')),
            ],
            options={
                'verbose_name_plural': 'Сцена',
            },
        ),
    ]
