# Generated by Django 4.1.5 on 2023-01-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='balet',
        ),
        migrations.RemoveField(
            model_name='table',
            name='opera',
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('opera', models.CharField(max_length=100, verbose_name='Опера')),
                ('balet', models.CharField(max_length=100, verbose_name='Балет')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opera.table')),
            ],
        ),
    ]
